// eventsData.js

/**
 * A collection of upcoming real events in India.
 *
 * Disclaimer: The application deadlines and event dates for many events
 * in late 2026 and 2027 are estimated based on their typical annual
 * schedules. Please verify the exact dates on the official websites.
 */

const hackathons = [
  {
    id: 27,
    title: "HackOn 3.0",
    description: "A global virtual hackathon aimed at fostering innovation and bringing together developers from around the world to solve real-world problems.",
    organizer: "HackOn Foundation",
    location: "Online",
    deadline: "2025-10-25",
    eventDate: "2025-10-27",
    tags: ["Hackathon", "Global", "Innovation", "Tech"],
    isBookmarked: false,
    applyLink: "https://hackon.tech/",
    participants: 8000,
    type: "hackathon",
  },
  {
    id: 28,
    title: "Hackfest by IIT (ISM) Dhanbad",
    description: "The flagship competitive programming and hacking event of Concetto, the techno-management fest of IIT (ISM) Dhanbad.",
    organizer: "IIT (ISM) Dhanbad",
    location: "Dhanbad, Jharkhand",
    deadline: "2025-10-15",
    eventDate: "2025-10-25",
    tags: ["Hackathon", "University", "CP", "Cybersecurity"],
    isBookmarked: false,
    applyLink: "https://hackfest.tech/",
    participants: 1500,
    type: "hackathon",
  },
  {
    id: 29,
    title: "HackNITR 5.0",
    description: "One of East India's largest student-run hackathons, encouraging collaboration and building innovative solutions.",
    organizer: "NIT Rourkela",
    location: "Online",
    deadline: "2026-01-20",
    eventDate: "2026-02-07",
    tags: ["Hackathon", "Innovation", "University", "Tech"],
    isBookmarked: false,
    applyLink: "https://hacknitr.com/",
    participants: 4000,
    type: "hackathon",
  },
  {
    id: 30,
    title: "DevFest India 2025 Hackathon",
    description: "A community-run hackathon as part of the largest Google Developer Group conference in India.",
    organizer: "Google Developer Groups India",
    location: "Bengaluru, Karnataka",
    deadline: "2025-09-25",
    eventDate: "2025-09-28",
    tags: ["Hackathon", "Google", "Community", "Android", "Cloud"],
    isBookmarked: false,
    applyLink: "https://devfestindia.com/",
    participants: 1000,
    type: "hackathon",
  },
  {
    id: 200,
    title: "AI Future Hack 2025",
    description: "A hackathon focused on AI and machine learning solutions for real-world problems.",
    organizer: "AI Innovators Group",
    location: "Hyderabad, Telangana",
    deadline: "2025-11-10",
    eventDate: "2025-11-15",
    tags: ["Hackathon", "AI", "Machine Learning", "Innovation"],
    isBookmarked: false,
    applyLink: "https://aifuturehack.com/",
    participants: 2500,
    type: "hackathon",
  },
  {
    id: 201,
    title: "GreenTech Hackathon 2025",
    description: "Innovate for a sustainable future at this green technology hackathon.",
    organizer: "GreenTech Foundation",
    location: "Pune, Maharashtra",
    deadline: "2025-12-01",
    eventDate: "2025-12-10",
    tags: ["Hackathon", "Sustainability", "Environment", "Tech"],
    isBookmarked: false,
    applyLink: "https://greentechhack.com/",
    participants: 1800,
    type: "hackathon",
  },
  {
    id: 31,
    title: "Hack The Mountains 6.0",
    description: "A prominent hackathon focused on bringing out the creative and innovative potential of developers.",
    organizer: "Hack The Mountains Community",
   
    deadline: "2026-03-10",
    eventDate: "2026-03-20",
    tags: ["Hackathon", "Community", "Innovation"],
    isBookmarked: false,
    applyLink: "https://hackthemountains.tech/",
    participants: 3000,
    type: "hackathon",
  },
  {
    id: 32,
    title: "ETHIndia 2025",
    description: "The world's largest Ethereum hackathon, bringing together the Web3 community to build and collaborate on decentralized applications.",
    organizer: "ETHGlobal",
    location: "Bengaluru, Karnataka",
    deadline: "2025-11-15",
    eventDate: "2025-12-06",
    tags: ["Hackathon", "Web3", "Blockchain", "Ethereum"],
    isBookmarked: false,
    applyLink: "https://ethindia.co/",
    participants: 2000,
    type: "hackathon",
  },
  {
    id: 33,
    title: "HackVerse 5.0 by NIT Surathkal",
    description: "A 24-hour national level hackathon organized by NIT Surathkal, focusing on innovation and technology.",
    organizer: "NIT Surathkal",
    location: "Surathkal, Karnataka",
    deadline: "2026-02-01",
    eventDate: "2026-02-21",
    tags: ["Hackathon", "University", "Innovation", "Tech"],
    isBookmarked: false,
    applyLink: "https://hackverse.nitk.ac.in/",
    participants: 800,
    type: "hackathon",
  },
  {
    id: 34,
    title: "Hack-A-Bit 2026 by BITS Pilani",
    description: "One of India's premier student-run hackathons, part of the APOGEE tech fest of BITS Pilani.",
    organizer: "BITS Pilani",
    location: "Pilani, Rajasthan",
    deadline: "2026-03-20",
    eventDate: "2026-04-04",
    tags: ["Hackathon", "University", "Innovation"],
    isBookmarked: false,
    applyLink: "https://bits-apogee.org/",
    participants: 1000,
    type: "hackathon",
  },
  {
    id: 35,
    title: "Codefest by IIT BHU",
    description: "An annual coding festival with a diverse set of events including a competitive hackathon.",
    organizer: "IIT (BHU) Varanasi",
    location: "Varanasi, Uttar Pradesh",
    deadline: "2026-02-15",
    eventDate: "2026-03-01",
    tags: ["Hackathon", "CP", "University"],
    isBookmarked: false,
    applyLink: "https://codefest.iitbhu.ac.in/",
    participants: 1200,
    type: "hackathon",
  },
  {
    id: 36,
    title: "Hack In The North 6.0",
    description: "North India's largest student hackathon, hosted by IIIT Allahabad, promoting a culture of collaborative problem-solving.",
    organizer: "IIIT Allahabad",
    location: "Allahabad, Uttar Pradesh",
    deadline: "2026-03-30",
    eventDate: "2026-04-10",
    tags: ["Hackathon", "University", "Tech"],
    isBookmarked: false,
    applyLink: "https://hitn.tech/",
    participants: 700,
    type: "hackathon",
  },
];

const internships = [
  {
    id: 37,
    title: "Microsoft SDE Intern, Summer 2026",
    description: "An internship focused on software design and development at one of the world's leading technology companies.",
    organizer: "Microsoft",
    location: "Hyderabad, Bengaluru, Noida",
    deadline: "2025-11-15",
    eventDate: "2026-05-15",
    tags: ["Internship", "Big Tech", "Software Engineering"],
    isBookmarked: false,
    applyLink: "https://careers.microsoft.com/students/us/en/india-opportunities",
    participants: 1000,
    type: "internship",
  },
  {
    id: 38,
    title: "Amazon SDE Intern, Summer 2026",
    description: "Work on scalable, distributed systems and contribute to products impacting millions of customers worldwide.",
    organizer: "Amazon",
    location: "Bengaluru, Hyderabad, Chennai",
    deadline: "2025-11-30",
    eventDate: "2026-05-20",
    tags: ["Internship", "Big Tech", "Cloud", "Software"],
    isBookmarked: false,
    applyLink: "https://www.amazon.jobs/en/business_categories/student-programs",
    participants: 1500,
    type: "internship",
  },
  {
    id: 39,
    title: "Meta Software Engineer Intern, Summer 2026",
    description: "Build new features for Meta's products and contribute to the development of technologies like AI and the metaverse.",
    organizer: "Meta",
    location: "Bengaluru, Mumbai",
    deadline: "2025-10-31",
    eventDate: "2026-05-10",
    tags: ["Internship", "Big Tech", "AI/ML", "Social Media"],
    isBookmarked: false,
    applyLink: "https://www.metacareers.com/students",
    participants: 300,
    type: "internship",
  },
  {
    id: 40,
    title: "Adobe Research Intern, Summer 2026",
    description: "Conduct cutting-edge research in areas like computer vision, NLP, and machine learning, with opportunities to publish papers.",
    organizer: "Adobe",
    location: "Bengaluru, Noida",
    deadline: "2025-12-15",
    eventDate: "2026-05-15",
    tags: ["Internship", "Research", "AI/ML", "Computer Vision"],
    isBookmarked: false,
    applyLink: "https://careers.adobe.com/students",
    participants: 100,
    type: "internship",
  },
  {
    id: 41,
    title: "Goldman Sachs Summer Analyst, 2026",
    description: "A summer internship program providing exposure to the financial services industry and software development in a fintech environment.",
    organizer: "Goldman Sachs",
    location: "Bengaluru, Hyderabad",
    deadline: "2025-10-20",
    eventDate: "2026-05-10",
    tags: ["Internship", "Fintech", "Finance", "Software"],
    isBookmarked: false,
    applyLink: "https://www.goldmansachs.com/careers/students/",
    participants: 400,
    type: "internship",
  },
  {
    id: 42,
    title: "Atlassian SDE Intern, Summer 2026",
    description: "Help build products like Jira and Confluence that are used by millions of teams for collaboration and software development.",
    organizer: "Atlassian",
    location: "Bengaluru",
    deadline: "2025-11-05",
    eventDate: "2026-05-15",
    tags: ["Internship", "Collaboration Tools", "SaaS", "Software"],
    isBookmarked: false,
    applyLink: "https://www.atlassian.com/company/careers/students",
    participants: 150,
    type: "internship",
  },
  {
    id: 43,
    title: "Salesforce SDE Intern, Summer 2026",
    description: "An internship focused on cloud computing and building applications on the Salesforce platform.",
    organizer: "Salesforce",
    location: "Hyderabad, Bengaluru",
    deadline: "2025-11-25",
    eventDate: "2026-05-20",
    tags: ["Internship", "Cloud", "SaaS", "CRM"],
    isBookmarked: false,
    applyLink: "https://www.salesforce.com/company/careers/university-recruiting/",
    participants: 200,
    type: "internship",
  },
  {
    id: 44,
    title: "Nvidia Deep Learning Intern, Summer 2026",
    description: "Work on challenging projects in deep learning, GPU computing, and AI with the world leader in accelerated computing.",
    organizer: "Nvidia",
    location: "Pune, Bengaluru, Hyderabad",
    deadline: "2025-12-31",
    eventDate: "2026-06-01",
    tags: ["Internship", "AI/ML", "Deep Learning", "Hardware"],
    isBookmarked: false,
    applyLink: "https://www.nvidia.com/en-in/about-nvidia/careers/university-recruiting/",
    participants: 100,
    type: "internship",
  },
  {
    id: 45,
    title: "DE Shaw SDE Intern, Summer 2026",
    description: "A highly sought-after internship at a leading quantitative investment firm, working on complex financial software.",
    organizer: "D. E. Shaw India",
    location: "Hyderabad",
    deadline: "2025-09-30",
    eventDate: "2026-05-10",
    tags: ["Internship", "Fintech", "Quant", "HFT"],
    isBookmarked: false,
    applyLink: "https://www.deshawindia.com/careers",
    participants: 80,
    type: "internship",
  },
  {
    id: 46,
    title: "Uber SDE Intern, Summer 2026",
    description: "Develop and maintain large-scale systems that power Uber's ride-sharing and food delivery platforms.",
    organizer: "Uber",
    location: "Bengaluru, Hyderabad",
    deadline: "2025-11-10",
    eventDate: "2026-05-15",
    tags: ["Internship", "Mobility", "Scalability", "Software"],
    isBookmarked: false,
    applyLink: "https://www.uber.com/us/en/careers/university/",
    participants: 150,
    type: "internship",
  },
  {
    id: 47,
    title: "Qualcomm Wireless R&D Intern, Summer 2026",
    description: "Internship focusing on 5G, IoT, and other next-generation wireless technologies.",
    organizer: "Qualcomm",
    location: "Bengaluru, Hyderabad, Chennai",
    deadline: "2025-12-10",
    eventDate: "2026-06-01",
    tags: ["Internship", "5G", "IoT", "Hardware", "Wireless"],
    isBookmarked: false,
    applyLink: "https://www.qualcomm.com/company/careers/interns",
    participants: 250,
    type: "internship",
  },
  {
    id: 48,
    title: "Intel Hardware Engineering Intern, Summer 2026",
    description: "Work on the design, validation, and manufacturing of next-generation CPUs and chipsets.",
    organizer: "Intel",
    location: "Bengaluru",
    deadline: "2025-12-20",
    eventDate: "2026-06-01",
    tags: ["Internship", "Hardware", "VLSI", "Semiconductor"],
    isBookmarked: false,
    applyLink: "https://www.intel.in/content/www/in/en/jobs/locations/india.html",
    participants: 300,
    type: "internship",
  },
  {
    id: 49,
    title: "Oracle SDE Intern, Summer 2026",
    description: "Contribute to Oracle's cloud infrastructure, database systems, and enterprise software products.",
    organizer: "Oracle",
    location: "Bengaluru, Hyderabad",
    deadline: "2026-01-15",
    eventDate: "2026-05-25",
    tags: ["Internship", "Cloud", "Database", "Enterprise"],
    isBookmarked: false,
    applyLink: "https://www.oracle.com/in/careers/university/",
    participants: 500,
    type: "internship",
  },
  {
    id: 50,
    title: "Morgan Stanley Technology Analyst Intern, 2026",
    description: "An opportunity to work on technology solutions for a leading global financial services firm.",
    organizer: "Morgan Stanley",
    location: "Mumbai, Bengaluru",
    deadline: "2025-10-15",
    eventDate: "2026-05-10",
    tags: ["Internship", "Fintech", "Finance", "Enterprise"],
    isBookmarked: false,
    applyLink: "https://www.morganstanley.com/people-opportunities/students-graduates",
    participants: 300,
    type: "internship",
  },
  {
    id: 51,
    title: "Flipkart SDE Intern, Summer 2026",
    description: "Work on e-commerce platforms and solve complex problems in logistics, supply chain, and search.",
    organizer: "Flipkart",
    location: "Bengaluru",
    deadline: "2025-11-20",
    eventDate: "2026-05-20",
    tags: ["Internship", "E-commerce", "Software", "Startup"],
    isBookmarked: false,
    applyLink: "https://www.flipkartcareers.com/#!/service/student",
    participants: 400,
    type: "internship",
  },
  {
    id: 52,
    title: "ServiceNow SDE Intern, Summer 2026",
    description: "Develop on the Now Platform, an enterprise cloud computing solution for workflow automation.",
    organizer: "ServiceNow",
    location: "Hyderabad",
    deadline: "2025-12-01",
    eventDate: "2026-05-18",
    tags: ["Internship", "Cloud", "Enterprise", "Workflow"],
    isBookmarked: false,
    applyLink: "https://careers.servicenow.com/early-in-career",
    participants: 100,
    type: "internship",
  },
  {
    id: 53,
    title: "Texas Instruments Analog Design Intern, 2026",
    description: "Internship for electrical engineering students focusing on the design and verification of analog and mixed-signal integrated circuits.",
    organizer: "Texas Instruments",
    location: "Bengaluru",
    deadline: "2025-12-15",
    eventDate: "2026-05-20",
    tags: ["Internship", "Hardware", "Analog", "Semiconductor"],
    isBookmarked: false,
    applyLink: "https://careers.ti.com/locations-india/",
    participants: 150,
    type: "internship",
  },
  {
    id: 54,
    title: "SAP Labs SDE Intern, Summer 2026",
    description: "Contribute to the development of enterprise resource planning (ERP) software and cloud solutions.",
    organizer: "SAP Labs India",
    location: "Bengaluru",
    deadline: "2026-01-20",
    eventDate: "2026-06-01",
    tags: ["Internship", "ERP", "Enterprise", "Cloud"],
    isBookmarked: false,
    applyLink: "https://www.sap.com/india/about/careers/students-graduates.html",
    participants: 300,
    type: "internship",
  },
  {
    id: 55,
    title: "Intuit SDE Intern, Summer 2026",
    description: "Work on financial software products like QuickBooks and TurboTax, focusing on building user-centric solutions.",
    organizer: "Intuit",
    location: "Bengaluru",
    deadline: "2025-11-28",
    eventDate: "2026-05-20",
    tags: ["Internship", "Fintech", "SaaS", "Software"],
    isBookmarked: false,
    applyLink: "https://www.intuit.com/careers/university/",
    participants: 100,
    type: "internship",
  },
  {
    id: 56,
    title: "VMware SDE Intern, Summer 2026",
    description: "An internship focused on virtualization technology, cloud computing, and software-defined data centers.",
    organizer: "VMware",
    location: "Bengaluru, Pune",
    deadline: "2025-12-05",
    eventDate: "2026-05-25",
    tags: ["Internship", "Cloud", "Virtualization", "Infrastructure"],
    isBookmarked: false,
    applyLink: "https://careers.vmware.com/university",
    participants: 200,
    type: "internship",
  },
];

const competitions = [
  {
    id: 57,
    title: "TCS CodeVita Season 12",
    description: "A global coding contest by TCS, offering students a chance to win cash prizes and interview opportunities.",
    organizer: "Tata Consultancy Services",
    location: "Online",
    deadline: "2026-01-15",
    eventDate: "2026-02-25",
    tags: ["Competition", "Hiring", "CP", "Global"],
    isBookmarked: false,
    applyLink: "https://www.tcscodevita.com/",
    participants: 300000,
    type: "competition",
  },
  {
    id: 58,
    title: "Flipkart GRiD 6.0",
    description: "Flipkart's national-level hackathon for engineering students to solve real-world e-commerce challenges.",
    organizer: "Flipkart",
    location: "Online / Bengaluru (Finale)",
    deadline: "2026-07-20",
    eventDate: "2026-08-30",
    tags: ["Competition", "Hiring", "E-commerce", "Hackathon"],
    isBookmarked: false,
    applyLink: "https://unstop.com/competitions/flipkart-grid-60-software-development-challenge-flipkart-889813",
    participants: 200000,
    type: "competition",
  },
  {
    id: 59,
    title: "Google Code Jam 2026",
    description: "Google's prestigious global coding competition, attracting top programmers to solve complex algorithmic challenges.",
    organizer: "Google",
    location: "Online",
    deadline: "2026-03-01",
    eventDate: "2026-04-05",
    tags: ["Competition", "CP", "Algorithms", "Global"],
    isBookmarked: false,
    applyLink: "https://codingcompetitions.withgoogle.com/codejam",
    participants: 50000,
    type: "competition",
  },
  {
    id: 60,
    title: "EY Tech-a-Thon 2026",
    description: "A competition by EY for students and professionals to build innovative solutions for complex business problems using emerging technologies.",
    organizer: "EY",
    location: "Online",
    deadline: "2026-02-10",
    eventDate: "2026-03-05",
    tags: ["Competition", "Innovation", "Consulting", "Tech"],
    isBookmarked: false,
    applyLink: "https://www.ey.com/en_in/careers/ey-tech-a-thon",
    participants: 15000,
    type: "competition",
  },
  {
    id: 61,
    title: "Reliance TUP 8.0",
    description: "The Ultimate Pitch, a nationwide competition for college students to present innovative startup ideas.",
    organizer: "Reliance",
    location: "Online / Mumbai (Finale)",
    deadline: "2025-10-31",
    eventDate: "2026-01-20",
    tags: ["Competition", "Startup", "Business", "Innovation"],
    isBookmarked: false,
    applyLink: "https://unstop.com/competitions/the-ultimate-pitch-80-reliance-898246",
    participants: 50000,
    type: "competition",
  },
  {
    id: 62,
    title: "Deloitte Maverick 2026",
    description: "A business solutions competition for B-school students to tackle real-world business challenges.",
    organizer: "Deloitte",
    location: "Online / Campus Rounds",
    deadline: "2026-08-15",
    eventDate: "2026-09-30",
    tags: ["Competition", "Business", "Case Study", "Consulting"],
    isBookmarked: false,
    applyLink: "https://www2.deloitte.com/in/en/pages/careers/articles/campus-maverick.html",
    participants: 40000,
    type: "competition",
  },
  {
    id: 63,
    title: "L&T Techgium 2026",
    description: "An open innovation platform for engineering students to work on real-world challenges from L&T Technology Services.",
    organizer: "L&T Technology Services",
    location: "Online",
    deadline: "2026-01-25",
    eventDate: "2026-03-15",
    tags: ["Competition", "Engineering", "Innovation", "Core"],
    isBookmarked: false,
    applyLink: "https://techgium.ltts.com/",
    participants: 20000,
    type: "competition",
  },
  {
    id: 64,
    title: "Wipro Code-It-Like-A-Pro 2026",
    description: "A coding challenge by Wipro for students to showcase their programming skills and win prizes.",
    organizer: "Wipro",
    location: "Online",
    deadline: "2026-04-10",
    eventDate: "2026-04-25",
    tags: ["Competition", "Hiring", "CP", "Tech"],
    isBookmarked: false,
    applyLink: "https://unstop.com/competitions/code-it-like-a-pro-national-level-coding-challenge-wipro-887461",
    participants: 60000,
    type: "competition",
  },
  {
    id: 65,
    title: "Accenture Innovation Challenge 2026",
    description: "A themed competition challenging students to apply their tech skills to create disruptive solutions.",
    organizer: "Accenture",
    location: "Online",
    deadline: "2026-09-15",
    eventDate: "2026-10-20",
    tags: ["Competition", "Innovation", "Tech", "Social Impact"],
    isBookmarked: false,
    applyLink: "https://www.accenture.com/in-en/careers/accenture-innovation-challenge",
    participants: 30000,
    type: "competition",
  },
  {
    id: 66,
    title: "Samsung PRISM Program",
    description: "A student program where teams work with Samsung researchers on live R&D projects and publish papers.",
    organizer: "Samsung R&D Institute India",
    location: "Online / Campus-based",
    deadline: "2026-01-31",
    eventDate: "2026-03-01",
    tags: ["Competition", "Research", "AI/ML", "Innovation"],
    isBookmarked: false,
    applyLink: "https://www.samsung.com/in/samsung-prism/",
    participants: 5000,
    type: "competition",
  },
  {
    id: 67,
    title: "ICPC Amritapuri Regional Contest 2025",
    description: "The preliminary online round for the prestigious International Collegiate Programming Contest for teams in the Asia Amritapuri region.",
    organizer: "Amrita Vishwa Vidyapeetham",
    location: "Online",
    deadline: "2025-10-20",
    eventDate: "2025-11-09",
    tags: ["Competition", "CP", "Algorithms", "University"],
    isBookmarked: false,
    applyLink: "https://www.amrita.edu/events/icpc-preliminary-online-contest",
    participants: 3000,
    type: "competition",
  },
  {
    id: 68,
    title: "MyGov Innovation Challenges",
    description: "Various challenges and competitions hosted by the Indian government on the MyGov platform to crowdsource solutions.",
    organizer: "Government of India",
    location: "Online",
    deadline: "2026-12-31",
    eventDate: "2026-12-31",
    tags: ["Competition", "Government", "Social Impact", "Innovation"],
    isBookmarked: false,
    applyLink: "https://innovateindia.mygov.in/",
    participants: 100000,
    type: "competition",
  },
  {
    id: 69,
    title: "HackerEarth IndiaHacks 2026",
    description: "One of the largest competitive programming contests in India, with multiple tracks and huge prizes.",
    organizer: "HackerEarth",
    location: "Online",
    deadline: "2026-02-28",
    eventDate: "2026-03-15",
    tags: ["Competition", "CP", "Hackathon", "AI/ML"],
    isBookmarked: false,
    applyLink: "https://www.hackerearth.com/challenges/",
    participants: 80000,
    type: "competition",
  },
  {
    id: 70,
    title: "Bajaj Finserv ATOM",
    description: "A B-school competition to build cutting-edge solutions for the financial services industry.",
    organizer: "Bajaj Finserv",
    location: "Online / Pune (Finale)",
    deadline: "2026-08-25",
    eventDate: "2026-10-10",
    tags: ["Competition", "Fintech", "Business", "Case Study"],
    isBookmarked: false,
    applyLink: "https://unstop.com/competitions/atom-bajaj-finserv-895123",
    participants: 10000,
    type: "competition",
  },
];

const workshopsAndSeminars = [
  {
    id: 71,
    title: "Techfest, IIT Bombay 2026",
    description: "Asia's largest science and technology festival, featuring competitions, workshops, and lectures by tech luminaries.",
    organizer: "IIT Bombay",
    location: "Mumbai, Maharashtra",
    deadline: "2026-01-10",
    eventDate: "2026-01-17",
    tags: ["Seminar", "Workshop", "University", "Tech Fest"],
    isBookmarked: false,
    applyLink: "https://techfest.org/",
    participants: 175000,
    type: "seminar",
  },
  {
    id: 72,
    title: "AWS Summit India 2026",
    description: "A major cloud computing conference by Amazon Web Services to connect with peers and experts, and learn about AWS services.",
    organizer: "Amazon Web Services",
    location: "Bengaluru, Karnataka",
    deadline: "2026-05-10",
    eventDate: "2026-05-20",
    tags: ["Seminar", "Cloud", "AWS", "Tech"],
    isBookmarked: false,
    applyLink: "https://aws.amazon.com/events/summits/india/",
    participants: 15000,
    type: "seminar",
  },
  {
    id: 73,
    title: "Shaastra 2026, IIT Madras",
    description: "An annual technical festival of IIT Madras, known for its diverse events, workshops, and strong industry presence.",
    organizer: "IIT Madras",
    location: "Chennai, Tamil Nadu",
    deadline: "2026-01-20",
    eventDate: "2026-01-28",
    tags: ["Seminar", "Workshop", "University", "Tech Fest"],
    isBookmarked: false,
    applyLink: "https://shaastra.org/",
    participants: 50000,
    type: "seminar",
  },
  {
    id: 74,
    title: "PyCon India 2026",
    description: "The premier conference in India for the Python programming language community.",
    organizer: "Python Software Society of India",
    location: "Hyderabad, Telangana",
    deadline: "2026-09-01",
    eventDate: "2026-10-02",
    tags: ["Seminar", "Python", "Community", "Open Source"],
    isBookmarked: false,
    applyLink: "https://in.pycon.org/",
    participants: 2000,
    type: "seminar",
  },
  {
    id: 75,
    title: "NASSCOM Technology & Leadership Forum 2026",
    description: "India's flagship leadership conference, shaping the future of the technology industry.",
    organizer: "NASSCOM",
    location: "Mumbai, Maharashtra",
    deadline: "2026-02-01",
    eventDate: "2026-02-18",
    tags: ["Seminar", "Leadership", "Business", "Tech"],
    isBookmarked: false,
    applyLink: "https://nasscom.in/ntlf/",
    participants: 3000,
    type: "seminar",
  },
  {
    id: 76,
    title: "Kshitij 2026, IIT Kharagpur",
    description: "The largest techno-management fest in Asia, with a wide array of events from robotics to finance.",
    organizer: "IIT Kharagpur",
    location: "Kharagpur, West Bengal",
    deadline: "2026-01-15",
    eventDate: "2026-01-22",
    tags: ["Seminar", "Workshop", "University", "Tech Fest"],
    isBookmarked: false,
    applyLink: "https://ktj.in/",
    participants: 70000,
    type: "seminar",
  },
  {
    id: 77,
    title: "Google Cloud Summit India 2026",
    description: "A conference showcasing the latest in Google Cloud Platform, data analytics, and machine learning.",
    organizer: "Google Cloud",
    location: "Mumbai, Maharashtra",
    deadline: "2026-09-10",
    eventDate: "2026-09-25",
    tags: ["Seminar", "Cloud", "GCP", "AI/ML"],
    isBookmarked: false,
    applyLink: "https://cloud.withgoogle.com/summit/",
    participants: 10000,
    type: "seminar",
  },
  {
    id: 78,
    title: "Pragyan 2026, NIT Trichy",
    description: "A premier student-run techno-management festival with a strong emphasis on practical workshops and events.",
    organizer: "NIT Trichy",
    location: "Tiruchirappalli, Tamil Nadu",
    deadline: "2026-03-01",
    eventDate: "2026-03-12",
    tags: ["Seminar", "Workshop", "University", "Tech Fest"],
    isBookmarked: false,
    applyLink: "https://www.pragyan.org/",
    participants: 30000,
    type: "seminar",
  },
  {
    id: 79,
    title: "Microsoft Future Ready 2026",
    description: "Microsoft's flagship event in India for business and technology leaders to discuss digital transformation.",
    organizer: "Microsoft India",
    location: "Bengaluru, Karnataka",
    deadline: "2026-02-15",
    eventDate: "2026-03-05",
    tags: ["Seminar", "Business", "Cloud", "AI"],
    isBookmarked: false,
    applyLink: "https://www.microsoft.com/en-in/futureready/",
    participants: 5000,
    type: "seminar",
  },
  {
    id: 80,
    title: "React India 2026",
    description: "An international conference on React and React Native, bringing front-end developers together.",
    organizer: "React India Community",
    location: "Goa",
    deadline: "2026-08-20",
    eventDate: "2026-09-18",
    tags: ["Seminar", "Workshop", "JavaScript", "React", "Frontend"],
    isBookmarked: false,
    applyLink: "https://www.reactindia.io/",
    participants: 1000,
    type: "seminar",
  },
  {
    id: 81,
    title: "APOGEE 2026, BITS Pilani",
    description: "A Place of Gathering of Engineering Ecstasy, the annual technical festival of BITS Pilani.",
    organizer: "BITS Pilani",
    location: "Pilani, Rajasthan",
    deadline: "2026-03-15",
    eventDate: "2026-03-28",
    tags: ["Seminar", "Workshop", "University", "Tech Fest"],
    isBookmarked: false,
    applyLink: "https://bits-apogee.org/",
    participants: 20000,
    type: "seminar",
  },
  {
    id: 82,
    title: "DevOpsDays India 2026",
    description: "A conference series for DevOps practitioners, covering software development, IT infrastructure operations, and their intersection.",
    organizer: "DevOpsDays Community",
    location: "Bengaluru, Karnataka",
    deadline: "2026-10-01",
    eventDate: "2026-11-06",
    tags: ["Seminar", "DevOps", "Cloud", "CI/CD"],
    isBookmarked: false,
    applyLink: "https://devopsdays.org/events/2026-bangalore/welcome/",
    participants: 800,
    type: "seminar",
  },
  {
    id: 83,
    title: "Agile India 2026",
    description: "Asia's largest conference on Agile, Lean, and other lightweight software development methodologies.",
    organizer: "Agile India Community",
    location: "Bengaluru, Karnataka",
    deadline: "2026-02-20",
    eventDate: "2026-03-18",
    tags: ["Seminar", "Agile", "Software Development", "Project Management"],
    isBookmarked: false,
    applyLink: "https://www.agileindia.org/",
    participants: 2500,
    type: "seminar",
  },
  {
    id: 84,
    title: "Bengaluru Tech Summit 2025",
    description: "Asia's largest technology event, organized by the Government of Karnataka, covering IT, Biotech, and Deeptech.",
    organizer: "Govt. of Karnataka",
    location: "Bengaluru, Karnataka",
    deadline: "2025-11-10",
    eventDate: "2025-11-19",
    tags: ["Seminar", "Tech", "Biotech", "Government"],
    isBookmarked: false,
    applyLink: "https://www.bengalurutechsummit.com/",
    participants: 20000,
    type: "seminar",
  },
  {
    id: 85,
    title: "GDG DevFest Hyderabad 2025",
    description: "An annual developer festival hosted by Google Developer Group Hyderabad with sessions on Google technologies.",
    organizer: "GDG Hyderabad",
    location: "Hyderabad, Telangana",
    deadline: "2025-10-25",
    eventDate: "2025-11-08",
    tags: ["Seminar", "Workshop", "Google", "Community", "Tech"],
    isBookmarked: false,
    applyLink: "https://gdg.community.dev/gdg-hyderabad/",
    participants: 1500,
    type: "seminar",
  },
  {
    id: 86,
    title: "5G India Leadership Summit 2026",
    description: "A conference focusing on the rollout, challenges, and opportunities of 5G technology in India.",
    organizer: "Konnect Worldwide",
    location: "New Delhi",
    deadline: "2026-04-15",
    eventDate: "2026-04-28",
    tags: ["Seminar", "5G", "Telecom", "Leadership"],
    isBookmarked: false,
    applyLink: "https://www.5gindiasummit.com/",
    participants: 1000,
    type: "seminar",
  },
  {
    id: 87,
    title: "India Game Developer Conference (IGDC) 2025",
    description: "India's premier event for game developers, featuring talks, workshops, and an expo.",
    organizer: "IGDC",
    location: "Hyderabad, Telangana",
    deadline: "2025-10-20",
    eventDate: "2025-11-05",
    tags: ["Seminar", "Gaming", "Game Development", "Workshop"],
    isBookmarked: false,
    applyLink: "https://indiagdc.com/2025/",
    participants: 4000,
    type: "seminar",
  },
  {
    id: 88,
    title: "Tryst 2026, IIT Delhi",
    description: "North India's largest science, technological, and management festival with a host of events and workshops.",
    organizer: "IIT Delhi",
    location: "New Delhi",
    deadline: "2026-03-05",
    eventDate: "2026-03-14",
    tags: ["Seminar", "Workshop", "University", "Tech Fest"],
    isBookmarked: false,
    applyLink: "https://tryst-iitd.org/",
    participants: 60000,
    type: "seminar",
  },
  {
    id: 89,
    title: "Cyber Security Summit India 2026",
    description: "A national conference discussing the latest trends, threats, and strategies in cybersecurity.",
    organizer: "Exito Media",
    location: "Mumbai, Maharashtra",
    deadline: "2026-08-10",
    eventDate: "2026-08-25",
    tags: ["Seminar", "Cybersecurity", "Tech", "Security"],
    isBookmarked: false,
    applyLink: "https://cybersecuritysummit.in/",
    participants: 500,
    type: "seminar",
  },
  {
    id: 90,
    title: "AWS Community Day Bengaluru 2026",
    description: "A community-organized cloud conference with technical discussions by expert AWS users and industry leaders.",
    organizer: "AWS User Group Bengaluru",
    location: "Bengaluru, Karnataka",
    deadline: "2026-02-28",
    eventDate: "2026-03-14",
    tags: ["Seminar", "AWS", "Cloud", "Community"],
    isBookmarked: false,
    applyLink: "https://aws.amazon.com/developer/community/usergroups/bengaluru/",
    participants: 2000,
    type: "seminar",
  },
  {
    id: 91,
    title: "Cognizance 2026, IIT Roorkee",
    description: "The annual technical festival of IIT Roorkee with a plethora of events, workshops, and guest lectures.",
    organizer: "IIT Roorkee",
    location: "Roorkee, Uttarakhand",
    deadline: "2026-03-10",
    eventDate: "2026-03-20",
    tags: ["Seminar", "Workshop", "University", "Tech Fest"],
    isBookmarked: false,
    applyLink: "https://cognizance.org.in/",
    participants: 40000,
    type: "seminar",
  },
  {
    id: 92,
    title: "Fintech Festival India 2026",
    description: "A series of events across India culminating in a mega event that brings the fintech ecosystem together.",
    organizer: "Fintech Festival India",
    location: "Mumbai, Maharashtra",
    deadline: "2026-04-20",
    eventDate: "2026-05-06",
    tags: ["Seminar", "Fintech", "Finance", "Business"],
    isBookmarked: false,
    applyLink: "https://www.fintechfestivalindia.com/",
    participants: 5000,
    type: "seminar",
  },
  {
    id: 93,
    title: "Data Science & AI Summit 2026",
    description: "A conference dedicated to advancements in Data Science and Artificial Intelligence, with tracks for both industry and academia.",
    organizer: "Aegis School of Data Science",
    location: "Mumbai, Maharashtra",
    deadline: "2026-01-15",
    eventDate: "2026-01-30",
    tags: ["Seminar", "AI/ML", "Data Science", "Analytics"],
    isBookmarked: false,
    applyLink: "https://www.datasciencecongress.com/",
    participants: 1000,
    type: "seminar",
  },
  {
    id: 94,
    title: "Technex'26, IIT (BHU) Varanasi",
    description: "The annual techno-management festival of the Indian Institute of Technology (BHU) Varanasi.",
    organizer: "IIT (BHU) Varanasi",
    location: "Varanasi, Uttar Pradesh",
    deadline: "2026-02-20",
    eventDate: "2026-03-05",
    tags: ["Seminar", "Workshop", "University", "Tech Fest"],
    isBookmarked: false,
    applyLink: "https://technex.co.in/",
    participants: 35000,
    type: "seminar",
  },
  {
    id: 95,
    title: "The AI Summit India 2026",
    description: "Part of a global series, this summit connects AI innovators and business leaders to discuss practical applications of AI.",
    organizer: "Informa Tech",
    location: "Bengaluru, Karnataka",
    deadline: "2026-09-01",
    eventDate: "2026-09-15",
    tags: ["Seminar", "AI/ML", "Business", "Innovation"],
    isBookmarked: false,
    applyLink: "https://bengaluru.theaisummit.com/",
    participants: 2000,
    type: "seminar",
  },
  {
    id: 96,
    title: "Pluralsight LIVE India 2026",
    description: "A technology skills conference to learn from industry experts and get hands-on with the latest tech.",
    organizer: "Pluralsight",
    location: "Bengaluru, Karnataka",
    deadline: "2026-10-15",
    eventDate: "2026-11-04",
    tags: ["Seminar", "Workshop", "Tech Skills", "Learning"],
    isBookmarked: false,
    applyLink: "https://www.pluralsight.com/live",
    participants: 3000,
    type: "seminar",
  },
  {
    id: 97,
    title: "JSFoo 2026",
    description: "A conference for the JavaScript community in India, covering frameworks, tools, and the future of the language.",
    organizer: "HasGeek",
    location: "Bengaluru, Karnataka",
    deadline: "2026-08-01",
    eventDate: "2026-08-21",
    tags: ["Seminar", "JavaScript", "Frontend", "Web Development"],
    isBookmarked: false,
    applyLink: "https://hasgeek.com/jsfoo/",
    participants: 700,
    type: "seminar",
  },
  {
    id: 98,
    title: "TechSparks 2026",
    description: "YourStory's flagship event for the startup ecosystem, featuring talks, pitching sessions, and networking.",
    organizer: "YourStory",
    location: "Bengaluru, Karnataka",
    deadline: "2026-09-20",
    eventDate: "2026-10-10",
    tags: ["Seminar", "Startup", "Entrepreneurship", "Business"],
    isBookmarked: false,
    applyLink: "https://yourstory.com/techsparks",
    participants: 5000,
    type: "seminar",
  },
  {
    id: 99,
    title: "Concetto 2025, IIT (ISM) Dhanbad",
    description: "The annual techno-management festival of IIT (ISM) Dhanbad, with a wide range of technical and business events.",
    organizer: "IIT (ISM) Dhanbad",
    location: "Dhanbad, Jharkhand",
    deadline: "2025-10-10",
    eventDate: "2025-10-18",
    tags: ["Seminar", "Workshop", "University", "Tech Fest"],
    isBookmarked: false,
    applyLink: "https://concetto.in/",
    participants: 15000,
    type: "seminar",
  },
  {
    id: 100,
    title: "India Mobile Congress 2026",
    description: "The largest digital technology event in South Asia, covering telecom, 5G, IoT, and AI.",
    organizer: "Dept. of Telecommunications & COAI",
    location: "New Delhi",
    deadline: "2026-09-15",
    eventDate: "2026-10-08",
    tags: ["Seminar", "Telecom", "5G", "IoT", "Government"],
    isBookmarked: false,
    applyLink: "https://www.indiamobilecongress.com/",
    participants: 70000,
    type: "seminar",
  },
  {
    id: 101,
    title: "UiPath DevCon India 2026",
    description: "A developer conference focused on Robotic Process Automation (RPA) and AI-powered automation.",
    organizer: "UiPath",
    location: "Bengaluru, Karnataka",
    deadline: "2026-03-20",
    eventDate: "2026-04-09",
    tags: ["Seminar", "RPA", "Automation", "AI"],
    isBookmarked: false,
    applyLink: "https://www.uipath.com/events/developer-conference",
    participants: 2000,
    type: "seminar",
  },
  {
    id: 102,
    title: "Wissenaire'27, IIT Bhubaneswar",
    description: "The annual techno-management festival of IIT Bhubaneswar, promoting technology and innovation.",
    organizer: "IIT Bhubaneswar",
    location: "Bhubaneswar, Odisha",
    deadline: "2027-01-25",
    eventDate: "2027-02-05",
    tags: ["Seminar", "Workshop", "University", "Tech Fest"],
    isBookmarked: false,
    applyLink: "https://wissenaire.org/",
    participants: 10000,
    type: "seminar",
  },
  {
    id: 103,
    title: "Red Hat Summit Connect India 2026",
    description: "An event focused on open-source technologies, hybrid cloud, and enterprise automation.",
    organizer: "Red Hat",
    location: "Mumbai, Maharashtra",
    deadline: "2026-07-15",
    eventDate: "2026-08-04",
    tags: ["Seminar", "Open Source", "Cloud", "Linux"],
    isBookmarked: false,
    applyLink: "https://www.redhat.com/en/summit",
    participants: 1500,
    type: "seminar",
  },
  {
    id: 104,
    title: "Techkriti'26, IIT Kanpur",
    description: "An annual inter-collegiate technical and entrepreneurial festival with workshops and competitions.",
    organizer: "IIT Kanpur",
    location: "Kanpur, Uttar Pradesh",
    deadline: "2026-03-12",
    eventDate: "2026-03-21",
    tags: ["Seminar", "Workshop", "University", "Tech Fest"],
    isBookmarked: false,
    applyLink: "https://techkriti.org/",
    participants: 45000,
    type: "seminar",
  },
  {
    id: 105,
    title: "GIDS (Great International Developer Summit) 2026",
    description: "India's largest software developer conference, covering a wide range of technologies and practices.",
    organizer: "Saltmarch Media",
    location: "Bengaluru, Karnataka",
    deadline: "2026-04-10",
    eventDate: "2026-04-21",
    tags: ["Seminar", "Software Development", "Tech", "Workshop"],
    isBookmarked: false,
    applyLink: "https://developersummit.com/",
    participants: 6000,
    type: "seminar",
  },
  {
    id: 106,
    title: "Aaruush'26, SRMIST",
    description: "A national-level techno-management fest organized by students of SRM Institute of Science and Technology.",
    organizer: "SRMIST",
    location: "Chennai, Tamil Nadu",
    deadline: "2026-09-15",
    eventDate: "2026-09-25",
    tags: ["Seminar", "Workshop", "University", "Tech Fest"],
    isBookmarked: false,
    applyLink: "https://aaruush.org/",
    participants: 50000,
    type: "seminar",
  },
  {
    id: 107,
    title: "Postman API Summit India 2026",
    description: "A conference for developers, testers, and product managers focused on API design, development, and lifecycle management.",
    organizer: "Postman",
    location: "Bengaluru, Karnataka",
    deadline: "2026-08-01",
    eventDate: "2026-08-19",
    tags: ["Seminar", "API", "Software Development", "Workshop"],
    isBookmarked: false,
    applyLink: "https://www.postman.com/events/postman-summit/",
    participants: 3000,
    type: "seminar",
  },
  {
    id: 108,
    title: "Hashnode Hackerverse India 2026",
    description: "A conference bringing together the developer community for talks, networking, and celebrating the spirit of blogging and open source.",
    organizer: "Hashnode",
    location: "Bengaluru, Karnataka",
    deadline: "2026-06-15",
    eventDate: "2026-07-04",
    tags: ["Seminar", "Community", "Blogging", "Open Source"],
    isBookmarked: false,
    applyLink: "https://hashnode.com/events",
    participants: 1000,
    type: "seminar",
  },
  {
    id: 109,
    title: "Advaita'26, IIIT Bhubaneswar",
    description: "The annual technical festival of IIIT Bhubaneswar, with a focus on emerging technologies and innovation.",
    organizer: "IIIT Bhubaneswar",
    location: "Bhubaneswar, Odisha",
    deadline: "2026-01-20",
    eventDate: "2026-02-01",
    tags: ["Seminar", "Workshop", "University", "Tech Fest"],
    isBookmarked: false,
    applyLink: "https://advaita.io/",
    participants: 8000,
    type: "seminar",
  },
  {
    id: 110,
    title: "FOSSASIA Summit India Satellite Event 2026",
    description: "A community event celebrating Free and Open Source Software, with talks and workshops on various FOSS technologies.",
    organizer: "FOSSASIA Community",
    location: "Pune, Maharashtra",
    deadline: "2026-07-25",
    eventDate: "2026-08-08",
    tags: ["Seminar", "Open Source", "FOSS", "Community"],
    isBookmarked: false,
    applyLink: "https://events.fossasia.org/",
    participants: 500,
    type: "seminar",
  },
  {
    id: 111,
    title: "Esprit'26, IIIT Lucknow",
    description: "The annual techno-cultural and management festival of IIIT Lucknow, blending tech events with cultural activities.",
    organizer: "IIIT Lucknow",
    location: "Lucknow, Uttar Pradesh",
    deadline: "2026-03-01",
    eventDate: "2026-03-12",
    tags: ["Seminar", "Workshop", "University", "Tech Fest"],
    isBookmarked: false,
    applyLink: "https://esprit.iiitl.ac.in/",
    participants: 7000,
    type: "seminar",
  },
  {
    id: 112,
    title: "Oracle CloudWorld Tour India 2026",
    description: "Oracle's flagship conference to explore cloud infrastructure, databases, and applications.",
    organizer: "Oracle",
    location: "Mumbai, Maharashtra",
    deadline: "2026-02-20",
    eventDate: "2026-03-11",
    tags: ["Seminar", "Cloud", "Database", "Enterprise"],
    isBookmarked: false,
    applyLink: "https://www.oracle.com/cloudworld-tour/",
    participants: 4000,
    type: "seminar",
  },
  {
    id: 113,
    title: "Srijan'26, Jadavpur University",
    description: "The science and technology festival of Jadavpur University, known for its strong focus on core engineering and science events.",
    organizer: "Jadavpur University",
    location: "Kolkata, West Bengal",
    deadline: "2026-02-15",
    eventDate: "2026-02-28",
    tags: ["Seminar", "Workshop", "University", "Engineering"],
    isBookmarked: false,
    applyLink: "https://srijanju.in/",
    participants: 10000,
    type: "seminar",
  },
  {
    id: 114,
    title: "GitHub Satellite India 2026",
    description: "A conference by GitHub for the developer community in India to learn about new products and best practices in software development.",
    organizer: "GitHub",
    location: "Bengaluru, Karnataka",
    deadline: "2026-03-01",
    eventDate: "2026-03-25",
    tags: ["Seminar", "DevOps", "Open Source", "Community"],
    isBookmarked: false,
    applyLink: "https://github.com/events/satellite",
    participants: 2500,
    type: "seminar",
  },
  {
    id: 115,
    title: "FinovateAsia India 2026",
    description: "A conference focusing on financial technology innovation, with demos and talks from leading fintech companies.",
    organizer: "Finovate",
    location: "Mumbai, Maharashtra",
    deadline: "2026-10-10",
    eventDate: "2026-10-28",
    tags: ["Seminar", "Fintech", "Innovation", "Finance"],
    isBookmarked: false,
    applyLink: "https://informaconnect.com/finovateasia/",
    participants: 800,
    type: "seminar",
  },
  {
    id: 116,
    title: "Kurukshetra'27, CEG Anna University",
    description: "An international techno-management fest hosted at the College of Engineering, Guindy, with a UNESCO patronage.",
    organizer: "CEG, Anna University",
    location: "Chennai, Tamil Nadu",
    deadline: "2027-02-01",
    eventDate: "2027-02-14",
    tags: ["Seminar", "Workshop", "University", "Tech Fest"],
    isBookmarked: false,
    applyLink: "https://kurukshetra.org.in/",
    participants: 25000,
    type: "seminar",
  },
  {
    id: 117,
    title: "SAP TechEd India 2026",
    description: "SAP's premier tech conference for developers, IT professionals, and enterprise architects to learn about SAP technologies.",
    organizer: "SAP",
    location: "Bengaluru, Karnataka",
    deadline: "2026-10-20",
    eventDate: "2026-11-12",
    tags: ["Seminar", "ERP", "Enterprise", "Cloud"],
    isBookmarked: false,
    applyLink: "https://www.sap.com/teched",
    participants: 5000,
    type: "seminar",
  },
  {
    id: 118,
    title: "GraVITas'26, VIT Vellore",
    description: "An international techno-management knowledge carnival at Vellore Institute of Technology.",
    organizer: "VIT Vellore",
    location: "Vellore, Tamil Nadu",
    deadline: "2026-09-18",
    eventDate: "2026-09-28",
    tags: ["Seminar", "Workshop", "University", "Tech Fest"],
    isBookmarked: false,
    applyLink: "https://gravitas.vit.ac.in/",
    participants: 30000,
    type: "seminar",
  },
  {
    id: 119,
    title: "Atlassian Community Day India 2026",
    description: "A community-led event for users of Atlassian products like Jira, Confluence, and Bitbucket to share knowledge and best practices.",
    organizer: "Atlassian Community",
    location: "Bengaluru, Karnataka",
    deadline: "2026-08-15",
    eventDate: "2026-09-05",
    tags: ["Seminar", "Community", "Agile", "DevOps"],
    isBookmarked: false,
    applyLink: "https://ace.atlassian.com/",
    participants: 1000,
    type: "seminar",
  },
  {
    id: 120,
    title: "Twilio SIGNAL India 2026",
    description: "A developer conference focused on the future of communications, APIs, and customer engagement.",
    organizer: "Twilio",
    location: "Bengaluru, Karnataka",
    deadline: "2026-07-10",
    eventDate: "2026-07-29",
    tags: ["Seminar", "API", "Communications", "Cloud"],
    isBookmarked: false,
    applyLink: "https://www.twilio.com/signal",
    participants: 1500,
    type: "seminar",
  },
  {
    id: 121,
    title: "Infotsav'27, IIITM Gwalior",
    description: "The annual techno-managerial festival of ABV-IIITM Gwalior, attracting participants from across the nation.",
    organizer: "IIITM Gwalior",
    location: "Gwalior, Madhya Pradesh",
    deadline: "2027-01-30",
    eventDate: "2027-02-11",
    tags: ["Seminar", "Workshop", "University", "Tech Fest"],
    isBookmarked: false,
    applyLink: "https://infotsav.in/",
    participants: 9000,
    type: "seminar",
  },
  {
    id: 122,
    title: "Global AI Bootcamp India 2026",
    description: "A free one-day event organized by local communities across India to learn about Artificial Intelligence on the Microsoft Azure platform.",
    organizer: "Global AI Community",
    location: "Multiple Cities (Pune, Chennai, etc.)",
    deadline: "2026-11-20",
    eventDate: "2026-12-05",
    tags: ["Workshop", "AI/ML", "Azure", "Community"],
    isBookmarked: false,
    applyLink: "https://globalai.community/global-ai-bootcamp/",
    participants: 3000,
    type: "workshop",
  },
  {
    id: 123,
    title: "Cloud Native Day India 2026",
    description: "A community conference focused on cloud native technologies like Kubernetes, Prometheus, and containers.",
    organizer: "Cloud Native Computing Foundation (CNCF)",
    location: "Pune, Maharashtra",
    deadline: "2026-05-15",
    eventDate: "2026-06-06",
    tags: ["Seminar", "Cloud Native", "Kubernetes", "Open Source"],
    isBookmarked: false,
    applyLink: "https://community.cncf.io/pune/",
    participants: 600,
    type: "seminar",
  },
  {
    id: 124,
    title: "MindSpark'26, COEP Pune",
    description: "The annual technical festival of the College of Engineering, Pune, with a legacy of promoting technical innovation.",
    organizer: "COEP Technological University",
    location: "Pune, Maharashtra",
    deadline: "2026-09-10",
    eventDate: "2026-09-19",
    tags: ["Seminar", "Workshop", "University", "Tech Fest"],
    isBookmarked: false,
    applyLink: "https://www.mind-spark.org/",
    participants: 20000,
    type: "seminar",
  },
  {
    id: 125,
    title: "Adobe MAX India 2026",
    description: "The creativity conference by Adobe, focusing on design, graphic arts, web development, and video production.",
    organizer: "Adobe",
    location: "Bengaluru, Karnataka",
    deadline: "2026-08-25",
    eventDate: "2026-09-16",
    tags: ["Seminar", "Design", "Creativity", "UI/UX", "Workshop"],
    isBookmarked: false,
    applyLink: "https://www.adobe.com/max.html",
    participants: 2000,
    type: "seminar",
  },
  {
    id: 126,
    title: "MongoDB.local India 2026",
    description: "A developer-focused conference to learn about the MongoDB data platform and modern application development.",
    organizer: "MongoDB",
    location: "Bengaluru, Karnataka",
    deadline: "2026-08-05",
    eventDate: "2026-08-26",
    tags: ["Seminar", "Database", "NoSQL", "Cloud"],
    isBookmarked: false,
    applyLink: "https://www.mongodb.com/events",
    participants: 1200,
    type: "seminar",
  },
];


const allEvents = [
  ...hackathons,
  ...internships,
  ...competitions,
  ...workshopsAndSeminars,
];

const events = allEvents.map(e => ({ ...e }));

module.exports = {
  hackathons,
  internships,
  competitions,
  workshopsAndSeminars,
  allEvents,
  events,
};